services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: comfit-website:latest
    container_name: comfit-website
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
      - web
      - default

networks:
  web:
    external: true
